/**:
  ros__parameters:
    common:
      lid_topic: "/livox/lidar"
      imu_topic: "/livox/accgyro"

    preprocess:
      lidar_type: 1                # int: Livox series LiDAR
      feature_extract_en: false    # bool
      scan_line: 6                 # int
      blind: 1.0                   # double

    initialization:
      cut_frame_num: 5             # int: must be positive integer
      orig_odom_freq: 10           # int: original Lidar frequency
      mean_acc_norm: 9.81          # double: 1 for livox built-in IMU
      online_refine_time: 20.0     # double: seconds
      data_accum_length: 500.0     # double
      Rot_LI_cov: [0.00005, 0.00005, 0.00005]
      Trans_LI_cov: [0.00001, 0.00001, 0.00001]

    mapping:
      filter_size_surf: 0.05       # double
      filter_size_map: 0.15        # double
      gyr_cov: 2.0                 # double
      acc_cov: 2.0                 # double
      b_acc_cov: 0.0001            # double
      b_gyr_cov: 0.0001            # double
      det_range: 100.0             # float

    publish:
      path_en: true                # bool
      scan_publish_en: true        # bool: false: close all the point cloud output
      dense_publish_en: true       # bool: false: low down the points number in a global-frame point clouds scan.
      scan_bodyframe_pub_en: false # bool: true: output the point cloud scans in IMU-body-frame

    pcd_save:
      pcd_save_en: false           # bool
      interval: -1                 # int: how many LiDAR frames saved in each pcd file;
                                   # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.
